import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import styles from "./RootLayout.module.css";
import Footer from "@/components/layout/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: "%s | Barbook",
    default: "Barbook",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        <main className={styles.main}>
          <div className="container">
            {children}
          </div>
        </main>

        <Footer />

      </body>
    </html>
  );
}
